flags = {
	"Abkhaz": "abkhazia",
	"Australian Aboriginal": "aborigines",
	"Acadian": "acadia",
	"Acehnese": "aceh",
	"Afghani": "afghanistan",
	"Ainu": "ainu",
	"Akwe": "akwe",
	"Al-Andalus": "almohad",
	"Albanian": "albania",
	"Aleut": "aleut",
	"Algerian": "algeria",
	"Amazigh": "amazigh",
	"Amazonian": "amazon",
	"American": "usa",
	"Andorran": "andorra",
	"Angolan": "angola",
	"Anishinaabe": "anishinaabe",
	"Antarctican": "antarctica",
	"Apache": "apache",
	"Arab": "arab",
	"Aragonese": "aragon",
	"Aramean": "aram",
	"Argentine": "argentina",
	"Armenian": "armenia",
	"Ashanti": "ashanti",
	"Assyrian": "assyria",
	"Asturian": "asturias",
	"Atlantean": "atlantis",
	"Australian": "australia",
	"Austrian": "austria",
	"Aymara": "aymara",
	"Azeri": "azerbaijan",
	"Aztec": "aztec",
	"Babylonian": "babylon",
	"Badian": "baden",
	"Barbarian": "barbarian",
	"Bashkir": "bashkortostan",
	"Basque": "euskadi",
	"Bavarian": "bavarian",
	"Belarusian": "belarus",
	"Belgian": "belgium",
	"Bengali": "bangladesh",
	"Benin": "benin_ancient",
	"Bhutanese": "bhutan",
	"Biafran": "biafra",
	"Boer": "boer",
	"Bolivian": "bolivia",
	"Bosnian-Herzegovinian": "bosnia",
	"Bosporan": "bosporus",
	"Brandenburgian": "brandenburg",
	"Brazilian": "brasil",
	"Breton": "brittany",
	"British": "united_kingdom",
	"Briton": "britannia",
	"Bulgarian": "bulgaria",
	"Burgundian": "burgundy",
	"Burkinabe": "burkina_faso",
	"Burmese": "myanmar",
	"Burundian": "burundi",
	"Byzantine": "byzantium",
	"Californian": "california",
	"Cambodian": "kampuchea",
	"Cameroonian": "cameroon",
	"Canadian": "canada",
	"Carthaginian": "cartago",
	"Castilian": "castile",
	"Catalan": "catalan",
	"Celtiberian": "celtiberian",
	"Central African": "car",
	"Central American": "central_america",
	"Cham": "cham",
	"Chananean": "chananea",
	"Chechen": "chechnya",
	"Cherokee": "keetoowah",
	"Chilean": "chile",
	"Chimu": "chimu",
	"Chinese": "china",
	"Chola": "chola",
	"Chumash": "chumash",
	"Colombian": "colombia",
	"Comanche": "comanche",
	"Confederate": "southern_cross",
	"Congolese": "dr_congo",
	"Cornish": "cornwall",
	"Corsican": "corsica",
	"Cossack": "cossack",
	"Costa Rican": "costa_rica",
	"Cree": "innu",
	"Crimean Tatar": "crimean_tatar",
	"Croatian": "croatia",
	"Cuban": "cuba",
	"Curonian": "courland",
	"Cypriot": "cyprus",
	"Czech": "czech",
	"Dahomean": "dahomey",
	"Danish": "denmark",
	"Dominican": "dominica",
	"Dominicano": "dominican_republic",
	"Dryad": "dryad",
	"Dutch": "netherlands",
	"East German": "ddr",
	"East Timorese": "east_timor",
	"Ecuadorian": "ecuador",
	"Egyptian": "egypt_ancient",
	"Egyptian Arab": "egypt",
	"Elamite": "elam",
	"Emirati": "uae",
	"English": "england",
	"Eritrean": "eritrea",
	"Esperant": "esperanto",
	"Estonian": "estonia",
	"Ethiopian": "ethiopia",
	"Etruscan": "etruscan",
	"European": "europe",
	"Fijian": "fiji",
	"Filipino": "philippines",
	"Finnish": "finland",
	"Flemish": "flanders",
	"Franconian": "franconia",
	"French": "france",
	"Frisian": "frisia",
	"Gaelic": "gael",
	"Galician": "galicia",
	"Gallic": "gaul",
	"Georgian": "georgia",
	"German": "germany",
	"Ghanaian": "ghana",
	"Gokturk": "gokturk",
	"Greater Polish": "greater_poland",
	"Greek": "greece_ancient",
	"Greenlander": "greenland",
	"Grenadian": "grenada",
	"Guanche": "guanche",
	"Guarani": "guarani",
	"Guatemalan": "guatemala",
	"Gupta": "gupta",
	"Guyanese": "guyana",
	"Hacker": "hacker",
	"Haitian": "haiti",
	"Han": "han",
	"Hanoverian": "hanover",
	"Hanseatic": "hansa",
	"Hasinay": "caddo",
	"Hawaiian": "hawaii",
	"Hellenic": "greece",
	"Hessian": "hesse",
	"Himyarite": "himyar",
	"Hittite": "hittite",
	"Holy Roman": "hre",
	"Papal": "vatican",
	"Honduran": "honduras",
	"Hopi": "hopi",
	"Hungarian": "hungary",
	"Iberian": "iberian",
	"Icelandic": "iceland",
	"Illyrian": "illyria",
	"Inca": "inca",
	"Indian": "india",
	"Indonesian": "indonesia",
	"Inuit": "nunavut",
	"Iranian": "iran",
	"Iraqi": "iraq",
	"Irish": "ireland",
	"Iroquois": "iroquois",
	"Israeli": "israel",
	"Italian": "italy",
	"Ivoirian": "ivory_coast",
	"Jamaican": "jamaica",
	"Japanese": "japan",
	"Jolof": "jolof",
	"Kalmyk": "kalmykia",
	"Kanem-Bornu": "kanem-bornu",
	"Karelian": "karelia",
	"Kashmiri": "kashmir",
	"Kazakh": "kazakhstan",
	"Kenyan": "kenya",
	"Khazar": "khazaria",
	"Khwarezmian": "khwarezm",
	"Kongo": "kongo",
	"Korean": "korea_ancient",
	"Kosovar": "kosovo",
	"Kurdish": "kurd",
	"Kyrgyz": "kyrgyzstan",
	"Lankese": "srilanka",
	"Laotian": "laos",
	"Latvian": "latvia",
	"Lebanese": "lebanon",
	"Lendian": "lendian",
	"Leonese": "leon",
	"Libyan": "libya",
	"Liechtensteiner": "liechtenstein",
	"Lipka Tatar": "lipkatatar",
	"Lithuanian": "lithuania",
	"Lojbanistani": "jbonai",
	"Lorrain": "lorraine",
	"Luxembourgish": "luxembourg",
	"Maasai": "maasai",
	"Macedon": "macedon",
	"Macedonian": "macedonia",
	"Majapahit": "majapahit",
	"Malagasy": "madagascar",
	"Malawian": "malawi",
	"Malaysian": "malaysia",
	"Mali": "mali_ancient",
	"Malian": "mali",
	"Maltese": "malta",
	"Manchu": "manchuria",
	"Manx": "man",
	"Maori": "maori",
	"Mapuche": "mapuche",
	"Martian": "mars",
	"Mayan": "maya",
	"Mazovian": "mazovia",
	"Mecklenburgian": "mecklenburg",
	"Metis": "metis",
	"Mexican": "mexico",
	"Miao": "hainan",
	"Micronesian": "micronesia",
	"Mi'kmaq": "mikmaq",
	"Milanese": "milan",
	"Miskito": "miskito",
	"Mixtec": "mixtec",
	"Moldovan": "moldova",
	"Monegasque": "monaco_alternative",
	"Mongol": "mongolia",
	"Montenegrin": "montenegro",
	"Moravian": "moravia",
	"Mordvin": "mordovia",
	"Moroccan": "morocco",
	"Botswanan": "botswana",
	"Mozambican": "mozambique",
	"Mughal": "mughal",
	"Muskogee": "muskogee",
	"Mwiska": "mwiska",
	"Namibian": "namibia",
	"Navajo": "navajo",
	"Neapolitan": "naples",
	"Nepali": "nepal",
	"Nestorian": "nestoria",
	"Newfoundland": "newfoundland",
	"New Zealand": "newzealand",
	"Nicaraguan": "nicaragua",
	"Nigerian": "nigeria",
	"Nigerien": "niger",
	"Nimiipuu": "nez_perce",
	"Norman": "normandy",
	"North Korean": "north_korea",
	"Northumbrian": "northumbria",
	"Norwegian": "norway",
	"Nubian": "nubia",
	"Numidian": "numidia",
	"Nuu-chah-nulth": "nuu-chah-nulth",
	"Occitan": "occitania",
	"Ohlone": "ohlone",
	"Oldenburgian": "oldenburg",
	"Omani": "oman",
	"Ossetian": "ossetia",
	"Ostrogothic": "valknut",
	"Otomi": "otomi",
	"Ottoman": "ottoman",
	"Ozite": "oz",
	"Pakistani": "pakistan",
	"Palatinate": "palatinate",
	"Palestinian": "palestine",
	"Palmyrene": "palmyra",
	"Panamanian": "panama",
	"Papuan": "papua_newguinea",
	"Paraguayan": "paraguay",
	"Pashtun": "pashtun",
	"Persian": "iran_ancient",
	"Peruvian": "peru",
	"Phoenician": "phoenicia",
	"Piedmontese": "piedmont",
	"Pirate": "pirate",
	"Polish": "poland",
	"Polynesian": "polynesian",
	"Portuguese": "portugal",
	"Prussian": "prussia",
	"Puerto Rican": "puerto_rico",
	"P'urhepecha": "purhepecha",
	"Quebecois": "quebec",
	"Raramuri": "raramuri",
	"Riffian": "rif",
	"Rio-Grandense": "piratini",
	"Roman": "rome",
	"Romanian": "romania",
	"Russian": "russia",
	"Ruthenian": "kiev",
	"Rwandan": "rwanda",
	"Ryukyuan": "ryukyu",
	"Sahrawi": "sadr",
	"Salvadoran": "el_salvador",
	"Sami": "sapmi",
	"Sammarinese": "san_marino",
	"Samogitian": "samogitia",
	"Sarmatian": "sarmatia",
	"Saudi": "saudi_arabia",
	"Savoyard": "savoy",
	"Saxon": "saxony",
	"Schleswig-Holsteinian": "schleswig-holstein",
	"Scottish": "scotland",
	"Scythian": "scythia",
	"Seleucid": "seleucid",
	"Senegalese": "senegal",
	"Serbian": "serbia",
	"Shawnee": "shawnee",
	"Siberian": "siberia",
	"Sicilian": "sicily",
	"Sikh": "sikh",
	"Sikkimese": "sikkim",
	"Silesian": "silesia",
	"Singaporean": "singapore",
	"Sioux": "cheyenne",
	"Slavic": "slavic",
	"Slovakian": "slovakia",
	"Slovenian": "slovenia",
	"Somali": "somalia",
	"Songhai": "songhai",
	"Sorbian": "lusatia",
	"South African": "south_africa",
	"South American": "unasur",
	"South Korean": "korea",
	"South Vietnamese": "rvn",
	"South Yemeni": "south_yemen",
	"Soviet": "soviet",
	"Spanish": "spain",
	"Sri Vijaya": "srivijaya",
	"Sudanese": "sudan",
	"Sumerian": "sumeria",
	"Surinamese": "suriname",
	"Swazi": "swaziland",
	"Swedish": "sweden",
	"Swiss": "switzerland",
	"Syrian": "syria",
	"Taino": "taino",
	"Tairona": "tairona",
	"Taiwanese": "taiwan",
	"Tajik": "tajikistan",
	"Tanzanian": "tanzania",
	"Tatar": "tatarstan",
	"Knights Templar": "templar",
	"Teutonic": "teutonic_order",
	"Texan": "texas",
	"Thai": "thailand",
	"Thracian": "thrace",
	"Tibetan": "tibet",
	"Timurid": "timur",
	"Tocharian": "tocharian",
	"Togolese": "togo",
	"Toltec": "toltec",
	"Tongan": "tonga",
	"Transylvanian": "transylvania",
	"Tunisian": "tunisia",
	"Tupi": "tupi",
	"Turkish": "turkey",
	"Turkmen": "turkmenistan",
	"Tuvan": "tannu_tuva",
	"Tyrolian": "tyrol",
	"Ugandan": "uganda",
	"Ukrainian": "ukraine",
	"UN": "united_nations",
	"Uruguayan": "uruguay",
	"Uyghur": "uyghur",
	"Uzbek": "uzbekistan",
	"Vampire": "vampire",
	"Vandalic": "vandal",
	"Venetian": "venice",
	"Venezuelan": "venezuela",
	"Vermont": "vermont",
	"Vietnamese": "vietnam",
	"Viking": "viking",
	"Vincentian": "svg",
	"Visigothic": "visigoth",
	"Walloon": "wallonia",
	"Welsh": "wales",
	"Western Pomeranian": "pomerania",
	"Western Roman": "labarum",
	"West Indian": "west_indies_federation",
	"Westphalian": "westphalia",
	"Wuerttembergian": "wuerttemberg",
	"Yakut": "sakha",
	"Yemeni": "yemen",
	"Yucatecan": "yucatan",
	"Yugoslav": "yugoslavia",
	"Zapotec": "zapotec",
	"Zimbabwean": "zimbabwe",
	"Zulu": "zulu",
}

nations = (
	"random",
	"Abkhaz",
	"Australian Aboriginal",
	"Acadian",
	"Acehnese",
	"Afghani",
	"Ainu",
	"Akwe",
	"Al-Andalus",
	"Albanian",
	"Aleut",
	"Algerian",
	"Amazigh",
	"Amazonian",
	"American",
	"Andorran",
	"Angolan",
	"Anishinaabe",
	"Antarctican",
	"Apache",
	"Arab",
	"Aragonese",
	"Aramean",
	"Argentine",
	"Armenian",
	"Ashanti",
	"Assyrian",
	"Asturian",
	"Atlantean",
	"Australian",
	"Austrian",
	"Aymara",
	"Azeri",
	"Aztec",
	"Babylonian",
	"Badian",
	"Barbarian",
	"Bashkir",
	"Basque",
	"Bavarian",
	"Belarusian",
	"Belgian",
	"Bengali",
	"Benin",
	"Bhutanese",
	"Biafran",
	"Boer",
	"Bolivian",
	"Bosnian-Herzegovinian",
	"Bosporan",
	"Brandenburgian",
	"Brazilian",
	"Breton",
	"British",
	"Briton",
	"Bulgarian",
	"Burgundian",
	"Burkinabe",
	"Burmese",
	"Burundian",
	"Byzantine",
	"Californian",
	"Cambodian",
	"Cameroonian",
	"Canadian",
	"Carthaginian",
	"Castilian",
	"Catalan",
	"Celtiberian",
	"Central African",
	"Central American",
	"Cham",
	"Chananean",
	"Chechen",
	"Cherokee",
	"Chilean",
	"Chimu",
	"Chinese",
	"Chola",
	"Chumash",
	"Colombian",
	"Comanche",
	"Confederate",
	"Congolese",
	"Cornish",
	"Corsican",
	"Cossack",
	"Costa Rican",
	"Cree",
	"Crimean Tatar",
	"Croatian",
	"Cuban",
	"Curonian",
	"Cypriot",
	"Czech",
	"Dahomean",
	"Danish",
	"Dominican",
	"Dominicano",
	"Dryad",
	"Dutch",
	"East German",
	"East Timorese",
	"Ecuadorian",
	"Egyptian",
	"Egyptian Arab",
	"Elamite",
	"Emirati",
	"English",
	"Eritrean",
	"Esperant",
	"Estonian",
	"Ethiopian",
	"Etruscan",
	"European",
	"Fijian",
	"Filipino",
	"Finnish",
	"Flemish",
	"Franconian",
	"French",
	"Frisian",
	"Gaelic",
	"Galician",
	"Gallic",
	"Georgian",
	"German",
	"Ghanaian",
	"Gokturk",
	"Greater Polish",
	"Greek",
	"Greenlander",
	"Grenadian",
	"Guanche",
	"Guarani",
	"Guatemalan",
	"Gupta",
	"Guyanese",
	"Hacker",
	"Haitian",
	"Han",
	"Hanoverian",
	"Hanseatic",
	"Hasinay",
	"Hawaiian",
	"Hellenic",
	"Hessian",
	"Himyarite",
	"Hittite",
	"Holy Roman",
	"Papal",
	"Honduran",
	"Hopi",
	"Hungarian",
	"Iberian",
	"Icelandic",
	"Illyrian",
	"Inca",
	"Indian",
	"Indonesian",
	"Inuit",
	"Iranian",
	"Iraqi",
	"Irish",
	"Iroquois",
	"Israeli",
	"Italian",
	"Ivoirian",
	"Jamaican",
	"Japanese",
	"Jolof",
	"Kalmyk",
	"Kanem-Bornu",
	"Karelian",
	"Kashmiri",
	"Kazakh",
	"Kenyan",
	"Khazar",
	"Khwarezmian",
	"Kongo",
	"Korean",
	"Kosovar",
	"Kurdish",
	"Kyrgyz",
	"Lankese",
	"Laotian",
	"Latvian",
	"Lebanese",
	"Lendian",
	"Leonese",
	"Libyan",
	"Liechtensteiner",
	"Lipka Tatar",
	"Lithuanian",
	"Lojbanistani",
	"Lorrain",
	"Luxembourgish",
	"Maasai",
	"Macedon",
	"Macedonian",
	"Majapahit",
	"Malagasy",
	"Malawian",
	"Malaysian",
	"Mali",
	"Malian",
	"Maltese",
	"Manchu",
	"Manx",
	"Maori",
	"Mapuche",
	"Martian",
	"Mayan",
	"Mazovian",
	"Mecklenburgian",
	"Metis",
	"Mexican",
	"Miao",
	"Micronesian",
	"Mi'kmaq",
	"Milanese",
	"Miskito",
	"Mixtec",
	"Moldovan",
	"Monegasque",
	"Mongol",
	"Montenegrin",
	"Moravian",
	"Mordvin",
	"Moroccan",
	"Botswanan",
	"Mozambican",
	"Mughal",
	"Muskogee",
	"Mwiska",
	"Namibian",
	"Navajo",
	"Neapolitan",
	"Nepali",
	"Nestorian",
	"Newfoundland",
	"New Zealand",
	"Nicaraguan",
	"Nigerian",
	"Nigerien",
	"Nimiipuu",
	"Norman",
	"North Korean",
	"Northumbrian",
	"Norwegian",
	"Nubian",
	"Numidian",
	"Nuu-chah-nulth",
	"Occitan",
	"Ohlone",
	"Oldenburgian",
	"Omani",
	"Ossetian",
	"Ostrogothic",
	"Otomi",
	"Ottoman",
	"Ozite",
	"Pakistani",
	"Palatinate",
	"Palestinian",
	"Palmyrene",
	"Panamanian",
	"Papuan",
	"Paraguayan",
	"Pashtun",
	"Persian",
	"Peruvian",
	"Phoenician",
	"Piedmontese",
	"Pirate",
	"Polish",
	"Polynesian",
	"Portuguese",
	"Prussian",
	"Puerto Rican",
	"P'urhepecha",
	"Quebecois",
	"Raramuri",
	"Riffian",
	"Rio-Grandense",
	"Roman",
	"Romanian",
	"Russian",
	"Ruthenian",
	"Rwandan",
	"Ryukyuan",
	"Sahrawi",
	"Salvadoran",
	"Sami",
	"Sammarinese",
	"Samogitian",
	"Sarmatian",
	"Saudi",
	"Savoyard",
	"Saxon",
	"Schleswig-Holsteinian",
	"Scottish",
	"Scythian",
	"Seleucid",
	"Senegalese",
	"Serbian",
	"Shawnee",
	"Siberian",
	"Sicilian",
	"Sikh",
	"Sikkimese",
	"Silesian",
	"Singaporean",
	"Sioux",
	"Slavic",
	"Slovakian",
	"Slovenian",
	"Somali",
	"Songhai",
	"Sorbian",
	"South African",
	"South American",
	"South Korean",
	"South Vietnamese",
	"South Yemeni",
	"Soviet",
	"Spanish",
	"Sri Vijaya",
	"Sudanese",
	"Sumerian",
	"Surinamese",
	"Swazi",
	"Swedish",
	"Swiss",
	"Syrian",
	"Taino",
	"Tairona",
	"Taiwanese",
	"Tajik",
	"Tanzanian",
	"Tatar",
	"Knights Templar",
	"Teutonic",
	"Texan",
	"Thai",
	"Thracian",
	"Tibetan",
	"Timurid",
	"Tocharian",
	"Togolese",
	"Toltec",
	"Tongan",
	"Transylvanian",
	"Tunisian",
	"Tupi",
	"Turkish",
	"Turkmen",
	"Tuvan",
	"Tyrolian",
	"Ugandan",
	"Ukrainian",
	"UN",
	"Uruguayan",
	"Uyghur",
	"Uzbek",
	"Vampire",
	"Vandalic",
	"Venetian",
	"Venezuelan",
	"Vermont",
	"Vietnamese",
	"Viking",
	"Vincentian",
	"Visigothic",
	"Walloon",
	"Welsh",
	"Western Pomeranian",
	"Western Roman",
	"West Indian",
	"Westphalian",
	"Wuerttembergian",
	"Yakut",
	"Yemeni",
	"Yucatecan",
	"Yugoslav",
	"Zapotec",
	"Zimbabwean",
	"Zulu",
)
