flags = {
        "random": "random",
	"Abkhaz": "abkhazia",
	"Australian Aboriginal": "aborigines",
	"Abyssinian": "ethiopia_old",
	"Acadian": "acadia",
	"Acehnese": "aceh",
	"Acrean": "acre",
	"Afghani": "afghanistan",
	"African": "africa",
	"Ainu": "ainu",
	"Akwe": "akwe",
	"Andalusi": "almohad",
	"Al-Andalus": "almohad", # compat
	"Ålander": "aland",
	"Albanian": "albania",
	"Aleut": "aleut",
	"Algerian": "algeria",
	"Alsatian": "alsace",
	"Amazigh": "amazigh",
	"Amazonian": "amazon",
	"American": "usa",
	"Andorran": "andorra",
	"Angolan": "angola",
	"Anhaltian": "anhalt",
	"Animal Kingdom": "animals",
	"Anishinaabe": "anishinaabe",
	"Antarctican": "antarctica",
	"Antiguan and Barbudan": "antigua_and_barbuda",
	"Antillean": "netherlands_antilles",
	"Apache": "apache",
	"Arab": "arab",
	"Aragonese": "aragon",
	"Aramean": "aram",
	"Argentine": "argentina",
	"Armenian": "armenia",
	"Ashanti": "ashanti",
	"Assamese": "assam",
	"Assyrian": "assyria",
	"Asturian": "asturias",
	"Atlantean": "atlantis",
	"Australian": "australia",
	"Austrian": "austria",
	"Avar": "avar",
	"Aymara": "aymara",
	"Azeri": "azerbaijan",
	"Aztec": "aztec",
	"Babylonian": "babylon",
	"Badian": "baden",
	"Bahamian": "bahamas",
	"Bahraini": "bahrain",
	"Bangladeshi": "bangladesh",
	"Barbadian": "barbados",
	"Barbarian": "barbarian",
	"Bashkir": "bashkortostan",
	"Basque": "euskadi",
	"Bavarian": "bavarian",
	"Belarusian": "belarus",
	"Belgian": "belgium",
	"Belgic": "belgic",
	"Belizean": "belize",
	"Bengali": "bengal",
	"Beninese": "benin_ancient",
	"Benin": "benin_ancient",
	"Bhutanese": "bhutan",
	"Biafran": "biafra",
	"Bissau-Guinean": "guinea-bissau",
	"Boer": "boer",
	"Boian": "boii",
	"Bolivian": "bolivia",
	"Bosnian-Herzegovinian": "bosnia",
	"Bosporan": "bosporus",
	"Botswanan": "botswana",
	"Brandenburgian": "brandenburg",
	"Brazilian": "brasil",
	"Breton": "brittany",
	"British": "united_kingdom",
	"Briton": "britannia",
	"Bruneian": "brunei",
	"Bulgarian": "bulgaria",
	"Burgundian": "burgundy",
	"Burgundic": "burgundic",
	"Burkinabe": "burkina_faso", # compat
	"Burkinabé": "burkina_faso",
	"Burmese": "myanmar",
	"Burundian": "burundi",
	"Buryat": "buryatia",
	"Byzantine": "byzantium",
	"Californian": "california",
	"Cambodian": "kampuchea",
	"Cameroonian": "cameroon",
	"Canadian": "canada",
	"Cañari": "canar",
	"Cantonese": "cantonese",
	"Cape Verdean": "cape_verde",
	"Carantanian": "carantanian",
	"Carthaginian": "cartago",
	"Castilian": "castile",
	"Catalan": "catalan",
	"Celtiberian": "celtiberian",
	"Celtic": "celtic",
	"Central African": "car",
	"Central American": "central_america",
	"Central Lithuanian": "central_lithuania",
	"Chadian": "chad",
	"Cham": "cham",
	"Chananean": "chananea",
	"Chechen": "chechnya",
	"Cherokee": "keetoowah",
	"Chiapanec": "chiapas",
	"Chickasaw": "chickasaw",
	"Chilean": "chile",
	"Chimu": "chimu",
	"Chinese": "china",
	"Chinook": "clatsop",
	"Choctaw": "choctaw",
	"Chola": "chola",
	"Chrobatian": "chrobatian",
	"Chumash": "chumash",
	"Chuvash": "chuvashia",
	"Circassian": "adygea",
	"Colombian": "colombia",
	"Comanche": "comanche",
	"Comorian": "comoros",
	"Confederate": "southern_cross",
	"Brazzaville-Congolese": "r_congo",
	"Congolese": "dr_congo",
	"Cornish": "cornwall",
	"Corsican": "corsica",
	"Cossack": "cossack",
	"Costa Rican": "costa_rica",
	"Cree": "innu",
	"Cretan": "crete",
	"Crimean Tatar": "crimean_tatar",
	"Croatian": "croatia",
	"Crusader": "jerusalem",
	"Cuban": "cuba",
	"Curonian": "courland",
	"Cuyavian": "cuyavia",
	"Cypriot": "cyprus",
	"Cyrenaican": "cyrenaica",
	"Czechoslovakian": "czechoslovakia",
	"Czech": "czech",
	"Dacian": "dacian",
	"Dahomean": "dahomey",
	"Danish": "denmark",
	"Darfuri": "darfur",
	"Djiboutian": "djibouti",
	"Dominicano": "dominican_republic",
	"Dominican": "dominica",
	"Dryad": "dryad",
	"Dutch": "netherlands",
	"East German": "ddr",
	"East Timorese": "east_timor",
	"Ecuadorian": "ecuador",
	"Egyptian Arab": "egypt",
	"Egyptian": "egypt_ancient",
	"Elamite": "elam",
	"Emirati": "uae",
	"English": "england",
	"Epirote": "epirus",
	"Equatoguinean": "equatorial_guinea",
	"Eritrean": "eritrea",
	"Esperant": "esperanto",
	"Estonian": "estonia",
	"Ethiopian": "ethiopia",
	"Etruscan": "etruscan",
	"European": "europe",
	"Evenki": "evenkia",
	"Faroese": "faroes",
	"Fijian": "fiji",
	"Filipino": "philippines",
	"Finnish": "finland",
	"Flemish": "flanders",
	"Florentine": "florence",
	"Formosan": "formosan",
	"Franconian": "franconia",
	"Frankish": "france_old",
	"French": "france",
	"Frisian": "frisia",
	"Friulian": "friuli",
	"Fulani": "sokoto",
	"Gabonese": "gabon",
	"Gaelic": "gael",
	"Galician": "galicia",
	"Gallic": "gaul",
	"Gambian": "gambia",
	"Genoese": "liguria",
	"Georgian": "georgia",
	"Gepid": "gepid",
	"German Belgian": "dgb",
	"Germanic": "germanic",
	"German": "germany",
	"Ghanaian": "ghana_ancient",
	"Ghana": "ghana_ancient",
	"Ghaznavid": "ghaznavid",
	"Gokturk": "gokturk", # compat
	"Göktürk": "gokturk",
	"Golden Horde": "golden_horde",
	"Gothic": "gothic",
	"Greater Polish": "greater_poland",
	"Greek": "greece_ancient",
	"Greenlander": "greenland",
	"Grenadian": "grenada",
	"Guanche": "guanche",
	"Guarani": "guarani",
	"Guatemalan": "guatemala",
	"Guinean": "guinea",
	"Gupta": "gupta",
	"Guyanese": "guyana",
	"Hacker": "hacker",
	"Haitian": "haiti",
	"Hanoverian": "hanover",
	"Han": "han",
	"Hanseatic": "hansa",
	"Hasinay": "caddo",
	"Hawaiian": "hawaii",
	"Hellenic": "greece",
	"Helvetian": "helvetii",
	"Hephthalite": "hephthalite",
	"Hessian": "hesse",
	"Himyarite": "himyar",
	"Hittite": "hittite",
	"Holy Roman": "hre",
	"Papal": "vatican",
	"Honduran": "honduras",
	"Hopi": "hopi",
	"Hungarian": "hungary",
	"Hunnic": "hunnic",
	"Iberian": "iberian",
	"Icelandic": "iceland",
	"Illyrian": "illyria",
	"Inca": "inca",
	"Indian": "india",
	"Indo-European": "indoeuropean",
	"Indonesian": "indonesia",
	"Inuit": "nunavut",
	"Iranian": "iran",
	"Iraqi": "iraq",
	"Irish": "ireland",
	"Iroquois": "iroquois",
	"Israeli": "israel",
	"Israelite": "israel_ancient",
	"Italian Greek": "italian_greek",
	"Italian": "italy",
	"Ivoirian": "ivory_coast",
	"Jaffna": "jaffna",
	"Jamaican": "jamaica",
	"Japanese": "japan",
	"Jolof": "jolof",
	"Jordanian": "jordan",
	"Kalmyk": "kalmykia",
	"Kanem-Bornu": "kanem-bornu",
	"Karabakhi": "nagorno_karabakh",
	"Karelian": "karelia",
	"Karen": "karen",
	"Kashmiri": "kashmir",
	"Kashubian": "kashubia",
	"Katangan": "katanga",
	"Kazakh": "kazakhstan",
	"Kenyan": "kenya",
	"Khazar": "khazaria",
	"Khmer": "khmer",
	"Khoisan": "khoisan",
	"Khwarezmian": "khwarezm",
	"Kiribati": "kiribati",
	"Kittitian and Nevisian": "saint_kitts_and_nevis",
	"Komi": "komi",
	"Kongo": "kongo",
	"Korean": "korea_ancient",
	"Kosovar": "kosovo",
	"Kuna": "kuna_yala",
	"Kurdish": "kurd",
	"Kushan": "kushan",
	"Kuwaiti": "kuwait",
	"Kyrgyz": "kyrgyzstan",
	"Langobardic": "langobardic",
	"Lankese": "srilanka",
	"Laotian": "laos",
	"Latin": "latin_empire",
	"Latvian": "latvia",
	"Lebanese": "lebanon",
	"Lendian": "lendian",
	"Leonese": "leon",
	"Lesothoan": "lesotho",
	"Liberian": "liberia",
	"Liburnian": "liburnian",
	"Libyan": "libya",
	"Liechtensteiner": "liechtenstein",
	"Ligurian": "ligurian",
	"Lipka Tatar": "lipkatatar",
	"Lippian": "lippe",
	"Lithuanian": "lithuania",
	"Lojbanistani": "jbonai",
	"Lorrain": "lorraine",
	"Luwian": "luwian",
	"Luxembourgish": "luxembourg",
	"Lycian": "lycian",
	"Maasai": "maasai",
	"Macedonian": "macedonia",
	"Macedon": "macedon",
	"Majapahit": "majapahit",
	"Malagasy": "madagascar",
	"Malawian": "malawi",
	"Malaysian": "malaysia",
	"Maldivian": "maldives",
	"Malian": "mali_ancient",
	"Mali": "mali_ancient",
	"Maltese": "malta",
	"Mamluk": "mamluk",
	"Manchu": "manchuria",
	"Manx": "man",
	"Maori": "maori",
	"Mapuche": "mapuche",
	"Marathi": "marathi",
	"Marshallese": "marshall_islands",
	"Martian": "mars",
	"Mauritanian": "mauritania",
	"Mauritian": "mauritius",
	"Mayan": "maya",
	"Mazovian": "mazovia",
	"Mecklenburgian": "mecklenburg",
	"Median": "median",
	"Messapian": "messapian",
	"Métis": "metis",
	"Metis": "metis", # compat
	"Mexican": "mexico",
	"Miao": "hainan",
	"Micronesian": "micronesia",
	"Mi'kmaq": "mikmaq",
	"Milanese": "milan",
	"Miskito": "miskito",
	"Mitanni": "mitanni",
	"Mixtec": "mixtec",
	"Moldovan": "moldova",
	"Moluccan": "moluccas",
	"Monegasque": "monaco_alternative",
	"Mongol": "mongolia",
	"Mon": "mon",
	"Montenegrin": "montenegro",
	"Moravian": "moravia",
	"Mordvin": "mordovia",
	"Moroccan": "morocco",
	"Mozambican": "mozambique",
	"Mughal": "mughal",
	"Muscovite": "moscow",
	"Muskogee": "muskogee",
	"Mwiska": "mwiska",
	"Namibian": "namibia",
	"Nauruan": "nauru",
	"Navajo": "navajo",
	"Neapolitan": "naples",
	"Nenets": "nenetsia",
	"Nepali": "nepal",
	"Nestorian": "nestoria",
	"Newfoundland": "newfoundland",
	"New Zealand": "newzealand",
	"Nicaraguan": "nicaragua",
	"Nigerian": "nigeria",
	"Nigerien": "niger",
	"Nimíipuu": "nez_perce", # compat
	"Nimiipuu": "nez_perce",
	"Norman": "normandy",
	"North Korean": "north_korea",
	"Northumbrian": "northumbria",
	"Norwegian": "norway",
	"Novgorodian": "novgorod",
	"Nubian": "nubia",
	"Numidian": "numidia",
	"Nuu-chah-nulth": "nuu-chah-nulth",
	"Occitan": "occitania",
	"Ohlone": "ohlone",
	"Oldenburgian": "oldenburg",
	"Old Prussian": "prusai",
	"Omani": "oman",
	"Ossetian": "ossetia",
	"Ostrogothic": "valknut",
	"Otomi": "otomi", # compat
	"Otomí": "otomi",
	"Ottoman": "ottoman",
	"Ozite": "oz",
	"Paeonian": "paeonia",
	"Pakistani": "pakistan",
	"Palatinate": "palatinate",
	"Palestinian": "palestine",
	"Palmyrene": "palmyra",
	"Panamanian": "panama",
	"Papua New Guinean": "papua_newguinea",
	"Papuan": "west_papua",
	"Paraguayan": "paraguay",
	"Parthian": "parthia",
	"Pashtun": "pashtun",
	"Pelasgian": "pelasgian",
	"Persian": "iran_ancient",
	"Peruvian": "peru",
	"Phoenician": "phoenicia",
	"Phrygian": "phrygian",
	"Pictish": "pict",
	"Piedmontese": "piedmont",
	"Pirate": "pirate",
	"Polish": "poland",
	"Polynesian": "polynesian",
	"Pontic": "trebizond",
	"Portuguese": "portugal",
	"Prussian": "prussia",
	"Puerto Rican": "puerto_rico",
	"P'urhepecha": "purhepecha",
	"Qatari": "qatar",
	"Quebecois": "quebec",
	"Rapa Nui": "rapa_nui",
	"Raramuri": "raramuri",
	"Rhenish": "rhineland",
	"Riffian": "rif",
	"Rio-Grandense": "piratini",
	"Romanian": "romania",
	"Roman": "rome",
	"Romansh": "grisons",
	"Russian": "russia",
	"Rusyn": "rusyn",
	"Ruthenian": "kiev", # compat
	"Kievan Rus'": "kiev",
	"Rwandan": "rwanda",
	"Ryukyuan": "ryukyu",
	"Sabine": "sabinium",
	"Sahrawi": "sadr",
	"Saint Lucian": "saint_lucia",
	"Saka": "saka",
	"Salishan": "salish",
	"Salvadoran": "el_salvador",
	"Sami": "sapmi",
	"Sammarinese": "san_marino",
	"Samnite": "samnium",
	"Samoan": "samoa",
	"Samogitian": "samogitia",
	"Santomean": "sao_tome_and_principe",
	"Sardinian": "sardinia",
	"Sarmatian": "sarmatia",
	"Saudi": "saudi_arabia",
	"Savoyard": "savoy",
	"Saxon": "saxony",
	"Scanian": "scania",
	"Schleswig-Holsteinian": "schleswig-holstein",
	"Scottish Gaelic": "scottishgaelic",
	"Scottish": "scotland",
	"Scythian": "scythia",
	"Seleucid": "seleucid",
	"Seljuk": "seljuk",
	"Seminole": "seminole",
	"Senegalese": "senegal",
	"Serbian": "serbia",
	"Seychellois": "seychelles",
	"Shan": "shan",
	"Shawnee": "shawnee",
	"Sherpa": "sherpa",
	"Siberian": "siberia",
	"Sicilian": "sicily",
	"Sierra Leonean": "sierra_leone",
	"Sikh": "sikh",
	"Sikkimese": "sikkim",
	"Silesian": "silesia",
	"Singaporean": "singapore",
	"Sinhalese": "sinhalese",
	"Sioux": "cheyenne",
	"Slavic": "slavic",
	"Slovakian": "slovakia",
	"Slovenian": "slovenia",
	"Solomon Islander": "solomon_islands",
	"Somaliland": "somaliland",
	"Somali": "somalia",
	"Songhai": "songhai",
	"Sorbian": "lusatia",
	"Sotho": "lesotho_old",
	"South African": "south_africa",
	"South American": "unasur",
	"South Korean": "korea",
	"South Sudanese": "southern_sudan",
	"South Vietnamese": "rvn",
	"South Yemeni": "south_yemen",
	"Soviet": "soviet",
	"Spanish": "spain",
	"Sri Vijaya": "srivijaya",
	"Sudanese": "sudan",
	"Suebian": "suebian",
	"Sumerian": "sumeria",
	"Surinamese": "suriname",
	"Swahili": "swahili",
	"Swazi": "swaziland",
	"Swedish": "sweden",
	"Swiss": "switzerland",
	"Syrian": "syria",
	"Tahitian": "french_polynesia",
	"Taino": "taino",
	"Tairona": "tairona",
	"Taiwanese": "taiwan",
	"Tajik": "tajikistan",
	"Tanganyikan": "tanganyika",
	"Tanzanian": "tanzania",
	"Tatar": "tatarstan",
	"Knights Templar": "templar",
	"Teutonic": "teutonic_order",
	"Texan": "texas",
	"Thai": "thailand",
	"Thracian": "thrace",
	"Thuringian": "thuringia",
	"Tibetan": "tibet",
	"Timurid": "timur",
	"Tocharian": "tocharian",
	"Togolese": "togo",
	"Toltec": "toltec",
	"Tongan": "tonga",
	"Transnistrian": "transnistria",
	"Transylvanian": "transylvania",
	"Trinidadian and Tobagonian": "trinidad_and_tobago",
	"Tswana": "bophuthatswana",
	"Tuareg": "tuareg",
	"Tunisian": "tunisia",
	"Tupi": "tupi",
	"Turkish Cypriot": "trnc",
	"Turkmen": "turkmenistan",
	"Turkish": "turkey",
	"Tuvan": "tannu_tuva",
	"Tyrolian": "tyrol",
	"Ugandan": "uganda",
	"Ukrainian": "ukraine",
	"UN": "united_nations",
	"Urartian": "urartu",
	"Uruguayan": "uruguay",
	"Uyghur": "uyghur",
	"Uzbek": "uzbekistan",
	"Vampire": "vampire",
	"Vandalic": "vandal",
	"Vanuatuan": "vanuatu",
	"Vedic": "vedic",
	"Veletian": "veletian",
	"Venda": "venda",
	"Venetian": "venice",
	"Venetic": "venetic",
	"Venezuelan": "venezuela",
	"Vermont": "vermont",
	"Vietnamese": "vietnam",
	"Viking": "viking",
	"Vincentian": "svg",
	"Visigothic": "visigoth",
	"Vistulan": "vistulan",
	"Volapükan": "volapuk",
	"Volga Bulgar": "volga_bulgar",
	"Volga German": "volga_german",
	"Walloon": "wallonia",
	"Welsh": "wales",
	"Werewolf": "luna",
	"Western Pomeranian": "pomerania",
	"Western Roman": "labarum",
	"West Indian": "west_indies_federation",
	"Westphalian": "westphalia",
	"Wuerttembergian": "wuerttemberg",
	"Xhosa": "xhosa",
	"Xiongnu": "xiongnu",
	"Yakut": "sakha",
	"Yemeni": "yemen",
	"Yucatecan": "yucatan",
	"Yugoslav": "yugoslavia",
	"Zambian": "zambia",
	"Zanzibari": "zanzibar",
	"Zapotec": "zapotec",
	"Zhuang": "zhuang",
	"Zimbabwean": "zimbabwe",
	"Zulu": "zulu",
}

nations = [
	"random",
	"Abkhaz",
	"Australian Aboriginal",
	"Abyssinian",
	"Acadian",
	"Acehnese",
	"Acrean",
	"Afghani",
	"African",
	"Ainu",
	"Akwe",
	"Andalusi",
	"Ålander",
	"Albanian",
	"Aleut",
	"Algerian",
	"Alsatian",
	"Amazigh",
	"Amazonian",
	"American",
	"Andorran",
	"Angolan",
	"Anhaltian",
	"Animal Kingdom",
	"Anishinaabe",
	"Antarctican",
	"Antiguan and Barbudan",
	"Antillean",
	"Apache",
	"Arab",
	"Aragonese",
	"Aramean",
	"Argentine",
	"Armenian",
	"Ashanti",
	"Assamese",
	"Assyrian",
	"Asturian",
	"Atlantean",
	"Australian",
	"Austrian",
	"Avar",
	"Aymara",
	"Azeri",
	"Aztec",
	"Babylonian",
	"Badian",
	"Bahamian",
	"Bahraini",
	"Bangladeshi",
	"Barbadian",
	"Barbarian",
	"Bashkir",
	"Basque",
	"Bavarian",
	"Belarusian",
	"Belgian",
	"Belgic",
	"Belizean",
	"Bengali",
	"Beninese",
	"Benin",
	"Bhutanese",
	"Biafran",
	"Bissau-Guinean",
	"Boer",
	"Boian",
	"Bolivian",
	"Bosnian-Herzegovinian",
	"Bosporan",
	"Botswanan",
	"Brandenburgian",
	"Brazilian",
	"Breton",
	"British",
	"Briton",
	"Bruneian",
	"Bulgarian",
	"Burgundian",
	"Burgundic",
	"Burkinabé",
	"Burmese",
	"Burundian",
	"Buryat",
	"Byzantine",
	"Californian",
	"Cambodian",
	"Cameroonian",
	"Canadian",
	"Cañari",
	"Cantonese",
	"Cape Verdean",
	"Carantanian",
	"Carthaginian",
	"Castilian",
	"Catalan",
	"Celtiberian",
	"Celtic",
	"Central African",
	"Central American",
	"Central Lithuanian",
	"Chadian",
	"Cham",
	"Chananean",
	"Chechen",
	"Cherokee",
	"Chiapanec",
	"Chickasaw",
	"Chilean",
	"Chimu",
	"Chinese",
	"Chinook",
	"Choctaw",
	"Chola",
	"Chrobatian",
	"Chumash",
	"Chuvash",
	"Circassian",
	"Colombian",
	"Comanche",
	"Comorian",
	"Confederate",
	"Brazzaville-Congolese",
	"Congolese",
	"Cornish",
	"Corsican",
	"Cossack",
	"Costa Rican",
	"Cree",
	"Cretan",
	"Crimean Tatar",
	"Croatian",
	"Crusader",
	"Cuban",
	"Curonian",
	"Cuyavian",
	"Cypriot",
	"Cyrenaican",
	"Czechoslovakian",
	"Czech",
	"Dacian",
	"Dahomean",
	"Danish",
	"Darfuri",
	"Djiboutian",
	"Dominicano",
	"Dominican",
	"Dryad",
	"Dutch",
	"East German",
	"East Timorese",
	"Ecuadorian",
	"Egyptian Arab",
	"Egyptian",
	"Elamite",
	"Emirati",
	"English",
	"Epirote",
	"Equatoguinean",
	"Eritrean",
	"Esperant",
	"Estonian",
	"Ethiopian",
	"Etruscan",
	"European",
	"Evenki",
	"Faroese",
	"Fijian",
	"Filipino",
	"Finnish",
	"Flemish",
	"Florentine",
	"Formosan",
	"Franconian",
	"Frankish",
	"French",
	"Frisian",
	"Friulian",
	"Fulani",
	"Gabonese",
	"Gaelic",
	"Galician",
	"Gallic",
	"Gambian",
	"Genoese",
	"Georgian",
	"Gepid",
	"German Belgian",
	"Germanic",
	"German",
	"Ghanaian",
	"Ghana",
	"Ghaznavid",
	"Göktürk",
	"Golden Horde",
	"Gothic",
	"Greater Polish",
	"Greek",
	"Greenlander",
	"Grenadian",
	"Guanche",
	"Guarani",
	"Guatemalan",
	"Guinean",
	"Gupta",
	"Guyanese",
	"Hacker",
	"Haitian",
	"Hanoverian",
	"Han",
	"Hanseatic",
	"Hasinay",
	"Hawaiian",
	"Hellenic",
	"Helvetian",
	"Hephthalite",
	"Hessian",
	"Himyarite",
	"Hittite",
	"Holy Roman",
	"Papal",
	"Honduran",
	"Hopi",
	"Hungarian",
	"Hunnic",
	"Iberian",
	"Icelandic",
	"Illyrian",
	"Inca",
	"Indian",
	"Indo-European",
	"Indonesian",
	"Inuit",
	"Iranian",
	"Iraqi",
	"Irish",
	"Iroquois",
	"Israeli",
	"Israelite",
	"Italian Greek",
	"Italian",
	"Ivoirian",
	"Jaffna",
	"Jamaican",
	"Japanese",
	"Jolof",
	"Jordanian",
	"Kalmyk",
	"Kanem-Bornu",
	"Karabakhi",
	"Karelian",
	"Karen",
	"Kashmiri",
	"Kashubian",
	"Katangan",
	"Kazakh",
	"Kenyan",
	"Khazar",
	"Khmer",
	"Khoisan",
	"Khwarezmian",
	"Kiribati",
	"Kittitian and Nevisian",
	"Komi",
	"Kongo",
	"Korean",
	"Kosovar",
	"Kuna",
	"Kurdish",
	"Kushan",
	"Kuwaiti",
	"Kyrgyz",
	"Langobardic",
	"Lankese",
	"Laotian",
	"Latin",
	"Latvian",
	"Lebanese",
	"Lendian",
	"Leonese",
	"Lesothoan",
	"Liberian",
	"Liburnian",
	"Libyan",
	"Liechtensteiner",
	"Ligurian",
	"Lipka Tatar",
	"Lippian",
	"Lithuanian",
	"Lojbanistani",
	"Lorrain",
	"Luwian",
	"Luxembourgish",
	"Lycian",
	"Maasai",
	"Macedonian",
	"Macedon",
	"Majapahit",
	"Malagasy",
	"Malawian",
	"Malaysian",
	"Maldivian",
	"Malian",
	"Mali",
	"Maltese",
	"Mamluk",
	"Manchu",
	"Manx",
	"Maori",
	"Mapuche",
	"Marathi",
	"Marshallese",
	"Martian",
	"Mauritanian",
	"Mauritian",
	"Mayan",
	"Mazovian",
	"Mecklenburgian",
	"Median",
	"Messapian",
	"Métis",
	"Mexican",
	"Miao",
	"Micronesian",
	"Mi'kmaq",
	"Milanese",
	"Miskito",
	"Mitanni",
	"Mixtec",
	"Moldovan",
	"Moluccan",
	"Monegasque",
	"Mongol",
	"Mon",
	"Montenegrin",
	"Moravian",
	"Mordvin",
	"Moroccan",
	"Mozambican",
	"Mughal",
	"Muscovite",
	"Muskogee",
	"Mwiska",
	"Namibian",
	"Nauruan",
	"Navajo",
	"Neapolitan",
	"Nenets",
	"Nepali",
	"Nestorian",
	"Newfoundland",
	"New Zealand",
	"Nicaraguan",
	"Nigerian",
	"Nigerien",
	"Nimíipuu",
	"Norman",
	"North Korean",
	"Northumbrian",
	"Norwegian",
	"Novgorodian",
	"Nubian",
	"Numidian",
	"Nuu-chah-nulth",
	"Occitan",
	"Ohlone",
	"Oldenburgian",
	"Old Prussian",
	"Omani",
	"Ossetian",
	"Ostrogothic",
	"Otomí",
	"Ottoman",
	"Ozite",
	"Paeonian",
	"Pakistani",
	"Palatinate",
	"Palestinian",
	"Palmyrene",
	"Panamanian",
	"Papua New Guinean",
	"Papuan",
	"Paraguayan",
	"Parthian",
	"Pashtun",
	"Pelasgian",
	"Persian",
	"Peruvian",
	"Phoenician",
	"Phrygian",
	"Pictish",
	"Piedmontese",
	"Pirate",
	"Polish",
	"Polynesian",
	"Pontic",
	"Portuguese",
	"Prussian",
	"Puerto Rican",
	"P'urhepecha",
	"Qatari",
	"Quebecois",
	"Rapa Nui",
	"Raramuri",
	"Rhenish",
	"Riffian",
	"Rio-Grandense",
	"Romanian",
	"Roman",
	"Romansh",
	"Russian",
	"Rusyn",
	"Kievan Rus'",
	"Rwandan",
	"Ryukyuan",
	"Sabine",
	"Sahrawi",
	"Saint Lucian",
	"Saka",
	"Salishan",
	"Salvadoran",
	"Sami",
	"Sammarinese",
	"Samnite",
	"Samoan",
	"Samogitian",
	"Santomean",
	"Sardinian",
	"Sarmatian",
	"Saudi",
	"Savoyard",
	"Saxon",
	"Scanian",
	"Schleswig-Holsteinian",
	"Scottish Gaelic",
	"Scottish",
	"Scythian",
	"Seleucid",
	"Seljuk",
	"Seminole",
	"Senegalese",
	"Serbian",
	"Seychellois",
	"Shan",
	"Shawnee",
	"Sherpa",
	"Siberian",
	"Sicilian",
	"Sierra Leonean",
	"Sikh",
	"Sikkimese",
	"Silesian",
	"Singaporean",
	"Sinhalese",
	"Sioux",
	"Slavic",
	"Slovakian",
	"Slovenian",
	"Solomon Islander",
	"Somaliland",
	"Somali",
	"Songhai",
	"Sorbian",
	"Sotho",
	"South African",
	"South American",
	"South Korean",
	"South Sudanese",
	"South Vietnamese",
	"South Yemeni",
	"Soviet",
	"Spanish",
	"Sri Vijaya",
	"Sudanese",
	"Suebian",
	"Sumerian",
	"Surinamese",
	"Swahili",
	"Swazi",
	"Swedish",
	"Swiss",
	"Syrian",
	"Tahitian",
	"Taino",
	"Tairona",
	"Taiwanese",
	"Tajik",
	"Tanganyikan",
	"Tanzanian",
	"Tatar",
	"Knights Templar",
	"Teutonic",
	"Texan",
	"Thai",
	"Thracian",
	"Thuringian",
	"Tibetan",
	"Timurid",
	"Tocharian",
	"Togolese",
	"Toltec",
	"Tongan",
	"Transnistrian",
	"Transylvanian",
	"Trinidadian and Tobagonian",
	"Tswana",
	"Tuareg",
	"Tunisian",
	"Tupi",
	"Turkish Cypriot",
	"Turkmen",
	"Turkish",
	"Tuvan",
	"Tyrolian",
	"Ugandan",
	"Ukrainian",
	"UN",
	"Urartian",
	"Uruguayan",
	"Uyghur",
	"Uzbek",
	"Vampire",
	"Vandalic",
	"Vanuatuan",
	"Vedic",
	"Veletian",
	"Venda",
	"Venetian",
	"Venetic",
	"Venezuelan",
	"Vermont",
	"Vietnamese",
	"Viking",
	"Vincentian",
	"Visigothic",
	"Vistulan",
	"Volapükan",
	"Volga Bulgar",
	"Volga German",
	"Walloon",
	"Welsh",
	"Werewolf",
	"Western Pomeranian",
	"Western Roman",
	"West Indian",
	"Westphalian",
	"Wuerttembergian",
	"Xhosa",
	"Xiongnu",
	"Yakut",
	"Yemeni",
	"Yucatecan",
	"Yugoslav",
	"Zambian",
	"Zanzibari",
	"Zapotec",
	"Zhuang",
	"Zimbabwean",
	"Zulu",
]

