# Generated by Django 2.2.12 on 2021-10-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('id', models.SlugField()),
                ('message', models.CharField(max_length=1024)),
                ('patches', models.CharField(max_length=256)),
                ('capability', models.CharField(max_length=256)),
                ('version', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('available', models.IntegerField()),
                ('humans', models.IntegerField()),
                ('last_seen', models.DateTimeField()),
            ],
        ),
    ]
