# Generated by Django 2.2.12 on 2021-10-17 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.SlugField()),
                ('nation', models.CharField(max_length=256)),
                ('leader', models.CharField(max_length=256)),
                ('type', models.IntegerField(choices=[(0, '-'), (1, 'Dead'), (2, 'Barbarian'), (3, 'A.I.'), (4, 'Human')])),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.Server')),
            ],
        ),
    ]
